name: Java Release with Maven
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: docker.pkg.github.com
        server-username: USERNAME
        server-password: PASSWORD
    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Perform release
      run: mvn build-helper:parse-version versions:set \
          release:prepare \
          -DdevelopmentVersion =\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0-SNAPSHOT \
          release:perform --file pom.xml
      env:
        USERNAME: $GITHUB_ACTOR
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}

